### ISSUE TITLE
Desktop Safari

### ISSUE THREAD

**Issue by ethto** [digitalsara/animal-rescue-website#2]
Looks great! Not sure if these occur on other browsers, but it's a bit off for a split second on safari:

<img width="399" alt="screen shot 2018-01-09 at 6 31 44 pm" src="https://user-images.githubusercontent.com/22225270/34748692-c173e50e-f56b-11e7-9d49-6a17e54e6368.png">

<img width="371" alt="screen shot 2018-01-09 at 6 33 17 pm" src="https://user-images.githubusercontent.com/22225270/34748695-c2ac18b0-f56b-11e7-9915-ae55a2375c29.png">

**Comment by digitalsara** [comment]
Thanks @ethto!

Last screenshot has to look this way, otherwise my text would have to be too small to fit on one line.
